import { describe, expect, it } from 'vitest'
import { clearSkyIrradiance, DEFAULT_LINKE_TURBIDITY } from './clearSkyIrradiance'

/**
 * Reference values below were generated by an independent Python
 * transcription of the sea-level-simplified Ineichen & Perez (2002)
 * clear-sky equations (see clearSkyIrradiance.ts's module doc for the
 * exact citation), written separately from the TypeScript implementation
 * under test here so the two implementations don't share bugs. Air mass
 * uses the Kasten & Young (1989) formula. The Python script itself is a
 * from-scratch re-transcription of the published/documented equations,
 * not a copy of the TS source (matching the cross-check rigor used for
 * sunPosition in docs/decisions/0010-solar-position-algorithm.md).
 *
 * Tolerance: 0.01 W/m², enforced via `toBeCloseTo(expected, 2)` below.
 *
 * See docs/decisions/0011-clear-sky-irradiance-model.md for the model
 * choice, the fixed Linke turbidity value/source, and known limitations
 * (fixed turbidity, no site-altitude correction, fixed solar constant).
 */

describe('clearSkyIrradiance', () => {
  it('sun below the horizon returns zero irradiance', () => {
    const result = clearSkyIrradiance(-10)
    expect(result.direct).toBe(0)
    expect(result.diffuse).toBe(0)
  })

  it('sun exactly at the horizon returns zero irradiance', () => {
    const result = clearSkyIrradiance(0)
    expect(result.direct).toBe(0)
    expect(result.diffuse).toBe(0)
  })

  it('very low sun (2 degrees) — near-horizon, heavily attenuated', () => {
    const result = clearSkyIrradiance(2, DEFAULT_LINKE_TURBIDITY)
    expect(result.direct).toBeCloseTo(0.4957, 2)
    expect(result.diffuse).toBeCloseTo(2.4693, 2)
  })

  it('low sun (10 degrees)', () => {
    const result = clearSkyIrradiance(10, DEFAULT_LINKE_TURBIDITY)
    expect(result.direct).toBeCloseTo(55.6144, 2)
    expect(result.diffuse).toBeCloseTo(40.6462, 2)
  })

  it('mid altitude (30 degrees)', () => {
    const result = clearSkyIrradiance(30, DEFAULT_LINKE_TURBIDITY)
    expect(result.direct).toBeCloseTo(359.3013, 2)
    expect(result.diffuse).toBeCloseTo(91.5499, 2)
  })

  it('high altitude (60 degrees)', () => {
    const result = clearSkyIrradiance(60, DEFAULT_LINKE_TURBIDITY)
    expect(result.direct).toBeCloseTo(751.8487, 2)
    expect(result.diffuse).toBeCloseTo(123.1848, 2)
  })

  it('near-zenith (90 degrees)', () => {
    const result = clearSkyIrradiance(90, DEFAULT_LINKE_TURBIDITY)
    expect(result.direct).toBeCloseTo(898.8258, 2)
    expect(result.diffuse).toBeCloseTo(132.9126, 2)
  })

  it('clean atmosphere (low turbidity) increases the direct component at the same altitude', () => {
    const result = clearSkyIrradiance(30, 2.0)
    expect(result.direct).toBeCloseTo(468.5925, 2)
    expect(result.diffuse).toBeCloseTo(37.5944, 2)
  })

  it('hazy atmosphere (high turbidity) reduces direct and increases diffuse at the same altitude', () => {
    const result = clearSkyIrradiance(30, 6.0)
    expect(result.direct).toBeCloseTo(229.395, 2)
    expect(result.diffuse).toBeCloseTo(142.343, 2)
  })

  it('default turbidity parameter matches passing DEFAULT_LINKE_TURBIDITY explicitly', () => {
    const withDefault = clearSkyIrradiance(45)
    const withExplicit = clearSkyIrradiance(45, DEFAULT_LINKE_TURBIDITY)
    expect(withDefault).toEqual(withExplicit)
  })

  it('is a pure function: repeated calls with the same inputs return the same result', () => {
    const first = clearSkyIrradiance(37.5, 4.0)
    const second = clearSkyIrradiance(37.5, 4.0)
    expect(second).toEqual(first)
  })

  it('total (direct + diffuse) irradiance increases monotonically with sun altitude', () => {
    const altitudes = [2, 10, 20, 30, 45, 60, 75, 90]
    const totals = altitudes.map((alt) => {
      const { direct, diffuse } = clearSkyIrradiance(alt)
      return direct + diffuse
    })
    for (let i = 1; i < totals.length; i++) {
      expect(totals[i]).toBeGreaterThan(totals[i - 1])
    }
  })
})
