import { describe, expect, it } from 'vitest'
import { decomposeGhi } from './decomposeGhi'

/**
 * Reference values below were generated by an independent Python
 * transcription of the Erbs (1982) GHI-decomposition correlation (see
 * decomposeGhi.ts's module doc for the exact citation), written separately
 * from the TypeScript implementation under test here so the two
 * implementations don't share bugs. Committed at
 * `src/solar-physics/__verification__/decomposeGhi_reference.py` for
 * auditability (not run as part of the build/test suite) and optionally
 * cross-checks against the real upstream `pvlib.irradiance.erbs` reference
 * implementation when run with `--pvlib` — matching the cross-check rigor
 * used for `clearSkyIrradiance` (0011) and `sunPosition` (0010).
 *
 * Tolerance: 2 decimal places, enforced via `toBeCloseTo(expected, 2)`
 * below (i.e. `|actual - expected| < 0.005`).
 *
 * See docs/decisions/0014-ghi-decomposition-erbs.md for the model choice
 * and known limitations (no eccentricity correction, out-of-range kt
 * handling).
 */

const azimuth = 180 // unused by decomposeGhi; kept for a realistic SunPositionInput shape

describe('decomposeGhi', () => {
  it('sun below the horizon returns zero for both components', () => {
    const result = decomposeGhi(500, { altitude: -5, azimuth })
    expect(result.directWm2).toBe(0)
    expect(result.diffuseWm2).toBe(0)
  })

  it('sun exactly at the horizon returns zero for both components', () => {
    const result = decomposeGhi(500, { altitude: 0, azimuth })
    expect(result.directWm2).toBe(0)
    expect(result.diffuseWm2).toBe(0)
  })

  it('zero GHI returns zero for both components', () => {
    const result = decomposeGhi(0, { altitude: 45, azimuth })
    expect(result.directWm2).toBe(0)
    expect(result.diffuseWm2).toBe(0)
  })

  it('negative GHI returns zero for both components', () => {
    const result = decomposeGhi(-10, { altitude: 45, azimuth })
    expect(result.directWm2).toBe(0)
    expect(result.diffuseWm2).toBe(0)
  })

  it('NaN GHI returns zero rather than NaN', () => {
    const result = decomposeGhi(NaN, { altitude: 45, azimuth })
    expect(result.directWm2).toBe(0)
    expect(result.diffuseWm2).toBe(0)
  })

  it('NaN sun altitude returns zero rather than NaN', () => {
    const result = decomposeGhi(500, { altitude: NaN, azimuth })
    expect(result.directWm2).toBe(0)
    expect(result.diffuseWm2).toBe(0)
  })

  it('non-finite sun altitude (Infinity) returns zero rather than NaN', () => {
    const result = decomposeGhi(500, { altitude: Infinity, azimuth })
    expect(result.directWm2).toBe(0)
    expect(result.diffuseWm2).toBe(0)
  })

  it('heavily overcast (low clearness index, 50 W/m2 at 10 degrees altitude) — mostly diffuse', () => {
    const result = decomposeGhi(50, { altitude: 10, azimuth })
    expect(result.directWm2).toBeCloseTo(0.952, 2)
    expect(result.diffuseWm2).toBeCloseTo(49.048, 2)
    // Diffuse fraction should be very high (near 1) in the overcast regime.
    expect(result.diffuseWm2 / 50).toBeGreaterThan(0.95)
  })

  it('overcast midday (100 W/m2 at 30 degrees altitude)', () => {
    const result = decomposeGhi(100, { altitude: 30, azimuth })
    expect(result.directWm2).toBeCloseTo(1.3226, 2)
    expect(result.diffuseWm2).toBeCloseTo(98.6774, 2)
  })

  it('partly cloudy (400 W/m2 at 30 degrees altitude) — transition regime', () => {
    const result = decomposeGhi(400, { altitude: 30, azimuth })
    expect(result.directWm2).toBeCloseTo(213.3934, 2)
    expect(result.diffuseWm2).toBeCloseTo(186.6066, 2)
  })

  it('partly cloudy, higher sun (600 W/m2 at 45 degrees altitude)', () => {
    const result = decomposeGhi(600, { altitude: 45, azimuth })
    expect(result.directWm2).toBeCloseTo(366.8966, 2)
    expect(result.diffuseWm2).toBeCloseTo(233.1034, 2)
  })

  it('clear sky (900 W/m2 at 60 degrees altitude) — mostly direct/beam', () => {
    const result = decomposeGhi(900, { altitude: 60, azimuth })
    expect(result.directWm2).toBeCloseTo(743.997, 2)
    expect(result.diffuseWm2).toBeCloseTo(156.003, 2)
    // Diffuse fraction should be low (clear-sky regime) at high clearness index.
    expect(result.diffuseWm2 / 900).toBeLessThan(0.2)
  })

  it('clear sky at zenith (950 W/m2 at 90 degrees altitude)', () => {
    const result = decomposeGhi(950, { altitude: 90, azimuth })
    expect(result.directWm2).toBeCloseTo(715.2768, 2)
    expect(result.diffuseWm2).toBeCloseTo(234.7232, 2)
  })

  it('out-of-range clearness index (kt > 1, e.g. cloud-edge enhancement) is handled without blowing up', () => {
    const result = decomposeGhi(300, { altitude: 10, azimuth })
    expect(result.directWm2).toBeCloseTo(250.5, 2)
    expect(result.diffuseWm2).toBeCloseTo(49.5, 2)
    expect(result.directWm2).toBeGreaterThanOrEqual(0)
    expect(result.diffuseWm2).toBeGreaterThanOrEqual(0)
  })

  it('direct + diffuse conserve energy (sum equals GHI) across a sweep of altitudes and GHI values', () => {
    const altitudes = [1, 5, 10, 20, 30, 45, 60, 75, 90]
    const ghiValues = [1, 10, 50, 100, 200, 400, 600, 800, 1000, 1200]
    for (const alt of altitudes) {
      for (const ghi of ghiValues) {
        const { directWm2, diffuseWm2 } = decomposeGhi(ghi, {
          altitude: alt,
          azimuth,
        })
        expect(directWm2 + diffuseWm2).toBeCloseTo(ghi, 6)
      }
    }
  })

  it('direct and diffuse are always non-negative across a sweep of altitudes and GHI values', () => {
    const altitudes = [-10, 0, 0.5, 1, 5, 10, 30, 45, 60, 75, 90]
    const ghiValues = [-10, 0, 1, 50, 200, 500, 900, 1200, 1400]
    for (const alt of altitudes) {
      for (const ghi of ghiValues) {
        const { directWm2, diffuseWm2 } = decomposeGhi(ghi, {
          altitude: alt,
          azimuth,
        })
        expect(directWm2).toBeGreaterThanOrEqual(0)
        expect(diffuseWm2).toBeGreaterThanOrEqual(0)
      }
    }
  })

  it('diffuse fraction decreases monotonically as GHI (and thus clearness index) increases at a fixed sun altitude', () => {
    const ghiValues = [20, 50, 100, 200, 300, 400, 500, 600, 700, 800]
    const fractions = ghiValues.map((ghi) => {
      const { diffuseWm2 } = decomposeGhi(ghi, { altitude: 45, azimuth })
      return diffuseWm2 / ghi
    })
    for (let i = 1; i < fractions.length; i++) {
      expect(fractions[i]).toBeLessThanOrEqual(fractions[i - 1])
    }
  })

  it('is a pure function: repeated calls with the same inputs return the same result', () => {
    const first = decomposeGhi(450, { altitude: 37.5, azimuth: 210 })
    const second = decomposeGhi(450, { altitude: 37.5, azimuth: 210 })
    expect(second).toEqual(first)
  })

  it('azimuth does not affect the result (model depends only on altitude via zenith)', () => {
    const a = decomposeGhi(400, { altitude: 40, azimuth: 90 })
    const b = decomposeGhi(400, { altitude: 40, azimuth: 270 })
    expect(a).toEqual(b)
  })
})
