import { describe, expect, it } from 'vitest'
import {
  panelPowerOutput,
  DEFAULT_NOCT_C,
  type PanelSpec,
} from './panelPowerOutput'

/**
 * Reference values below were generated by an independent Python
 * re-transcription of the power-output model (rated-power linear
 * irradiance scaling + NOCT cell-temperature approximation +
 * temperature-coefficient derating + system losses), written separately
 * from the TypeScript implementation under test here so the two
 * implementations don't share bugs. Committed at
 * `src/solar-physics/__verification__/poaPower_reference.py` for
 * auditability (not run as part of the build/test suite).
 *
 * Tolerance: 4 decimal places, enforced via `toBeCloseTo(expected, 4)`.
 *
 * See docs/decisions/0013-poa-transposition-and-power-model.md for the
 * NOCT default and cell-temperature model choice.
 */

const panel: PanelSpec = {
  ratedWattsPeak: 400,
  efficiencyPercent: 21.0,
  areaM2: 1.9,
  tempCoefficientPercentPerC: -0.35,
}

describe('panelPowerOutput', () => {
  it('near-STC irradiance and mild ambient temperature', () => {
    const result = panelPowerOutput(1000, panel, 25, 14)
    expect(result).toBeCloseTo(306.375, 4)
  })

  it('hot ambient temperature reduces output relative to the same irradiance at 25C', () => {
    const atMildTemp = panelPowerOutput(1000, panel, 25, 14)
    const atHotTemp = panelPowerOutput(1000, panel, 40, 14)
    expect(atHotTemp).toBeLessThan(atMildTemp)
    expect(atHotTemp).toBeCloseTo(288.315, 4)
  })

  it('half irradiance roughly halves output (temperature effect is a second-order adjustment)', () => {
    const full = panelPowerOutput(1000, panel, 25, 14)
    const half = panelPowerOutput(500, panel, 25, 14)
    expect(half).toBeCloseTo(162.5938, 4)
    // Not exactly half, since cell temperature (and thus the derate
    // factor) also depends on irradiance, but close.
    expect(half).toBeGreaterThan(full * 0.45)
    expect(half).toBeLessThan(full * 0.55)
  })

  it('cold ambient temperature increases output relative to the same irradiance at 25C', () => {
    const atMildTemp = panelPowerOutput(1000, panel, 25, 14)
    const atColdTemp = panelPowerOutput(1000, panel, 0, 14)
    expect(atColdTemp).toBeGreaterThan(atMildTemp)
    expect(atColdTemp).toBeCloseTo(336.475, 4)
  })

  it('a different panel/loss combination', () => {
    const otherPanel: PanelSpec = {
      ratedWattsPeak: 300,
      efficiencyPercent: 18.5,
      tempCoefficientPercentPerC: -0.4,
    }
    const result = panelPowerOutput(800, otherPanel, 30, 10)
    expect(result).toBeCloseTo(190.08, 4)
  })

  it('zero irradiance produces zero power', () => {
    const result = panelPowerOutput(0, panel, 25, 14)
    expect(result).toBe(0)
  })

  it('negative or non-finite irradiance produces zero power rather than NaN/negative', () => {
    expect(panelPowerOutput(-100, panel, 25, 14)).toBe(0)
    expect(panelPowerOutput(NaN, panel, 25, 14)).toBe(0)
    expect(panelPowerOutput(Infinity, panel, 25, 14)).not.toBeNaN()
  })

  it('output scales monotonically with irradiance, holding everything else fixed', () => {
    const irradiances = [50, 100, 250, 500, 750, 1000, 1200]
    const outputs = irradiances.map((poa) =>
      panelPowerOutput(poa, panel, 25, 14),
    )
    for (let i = 1; i < outputs.length; i++) {
      expect(outputs[i]).toBeGreaterThan(outputs[i - 1])
    }
  })

  it('output is always non-negative across a sweep of irradiance, temperature, and losses', () => {
    const irradiances = [0, 200, 600, 1000, 1400]
    const ambientTemps = [-20, 0, 25, 45, 60]
    const losses = [0, 10, 30, 60]
    for (const poa of irradiances) {
      for (const temp of ambientTemps) {
        for (const loss of losses) {
          const result = panelPowerOutput(poa, panel, temp, loss)
          expect(result).toBeGreaterThanOrEqual(0)
        }
      }
    }
  })

  it('higher system losses reduce output proportionally', () => {
    const noLosses = panelPowerOutput(1000, panel, 25, 0)
    const withLosses = panelPowerOutput(1000, panel, 25, 20)
    expect(withLosses).toBeCloseTo(noLosses * 0.8, 6)
  })

  it('a zero temperature coefficient means ambient temperature has no effect', () => {
    const flatPanel: PanelSpec = { ...panel, tempCoefficientPercentPerC: 0 }
    const atCold = panelPowerOutput(1000, flatPanel, -10, 14)
    const atHot = panelPowerOutput(1000, flatPanel, 45, 14)
    expect(atCold).toBeCloseTo(atHot, 8)
  })

  it('default NOCT (45C) matches passing DEFAULT_NOCT_C explicitly', () => {
    const withDefault = panelPowerOutput(800, panel, 25, 14)
    const withExplicit = panelPowerOutput(800, panel, 25, 14, DEFAULT_NOCT_C)
    expect(withDefault).toBe(withExplicit)
  })

  it('a lower NOCT reduces the temperature derating effect at high irradiance', () => {
    const highNoct = panelPowerOutput(1000, panel, 30, 14, 49)
    const lowNoct = panelPowerOutput(1000, panel, 30, 14, 40)
    // Lower NOCT -> cooler estimated cell temp -> less negative derating
    // (given a negative temp coefficient) -> higher output.
    expect(lowNoct).toBeGreaterThan(highNoct)
  })

  it('is a pure function: repeated calls with the same inputs return the same result', () => {
    const first = panelPowerOutput(650, panel, 22, 12)
    const second = panelPowerOutput(650, panel, 22, 12)
    expect(second).toBe(first)
  })
})
