import { describe, expect, it } from 'vitest'
import { poaIrradiance, DEFAULT_ALBEDO } from './poaIrradiance'

/**
 * Reference values below were generated by an independent Python
 * re-transcription of the isotropic sky-diffuse (Liu-Jordan) POA
 * transposition model, written separately from the TypeScript
 * implementation under test here so the two implementations don't share
 * bugs. Committed at
 * `src/solar-physics/__verification__/poaPower_reference.py` for
 * auditability (not run as part of the build/test suite).
 *
 * Tolerance: 4 decimal places, enforced via `toBeCloseTo(expected, 4)`.
 *
 * See docs/decisions/0013-poa-transposition-and-power-model.md for the
 * model choice (isotropic sky-diffuse vs. anisotropic models) and the
 * ground-reflection/albedo default.
 */

describe('poaIrradiance', () => {
  it('flat panel (tilt 0) with sun overhead: POA equals horizontal total (no ground reflection at tilt 0)', () => {
    const result = poaIrradiance(
      { direct: 800, diffuse: 100 },
      { altitude: 60, azimuth: 180 },
      0,
      180,
    )
    expect(result).toBeCloseTo(900.0, 4)
  })

  it('tilted panel facing the sun exactly: POA exceeds horizontal total', () => {
    const result = poaIrradiance(
      { direct: 800, diffuse: 100 },
      { altitude: 60, azimuth: 180 },
      30,
      180,
    )
    expect(result).toBeCloseTo(1029.1194, 4)
  })

  it('oblique sun (low altitude, azimuth offset from panel)', () => {
    const result = poaIrradiance(
      { direct: 800, diffuse: 100 },
      { altitude: 30, azimuth: 90 },
      40,
      180,
    )
    expect(result).toBeCloseTo(722.1938, 4)
  })

  it('mixed oblique case', () => {
    const result = poaIrradiance(
      { direct: 600, diffuse: 150 },
      { altitude: 45, azimuth: 200 },
      35,
      180,
    )
    expect(result).toBeCloseTo(964.8826, 4)
  })

  it('zero direct component: only diffuse + ground-reflected contribute', () => {
    const result = poaIrradiance(
      { direct: 0, diffuse: 50 },
      { altitude: 10, azimuth: 90 },
      30,
      180,
    )
    expect(result).toBeCloseTo(47.3205, 4)
  })

  it('sun nearly opposite the panel azimuth: direct component heavily reduced by AOI', () => {
    const result = poaIrradiance(
      { direct: 500, diffuse: 100 },
      { altitude: 20, azimuth: 0 },
      30,
      180,
    )
    expect(result).toBeCloseTo(101.3397, 4)
  })

  it('vertical panel (tilt 90), sun due south matching panel azimuth', () => {
    const result = poaIrradiance(
      { direct: 700, diffuse: 120 },
      { altitude: 50, azimuth: 180 },
      90,
      180,
    )
    expect(result).toBeCloseTo(729.3697, 4)
  })

  it('sun below the horizon returns zero, even with nonzero (physically inconsistent) horizontal irradiance', () => {
    const result = poaIrradiance(
      { direct: 0, diffuse: 0 },
      { altitude: -5, azimuth: 180 },
      30,
      180,
    )
    expect(result).toBeCloseTo(0.0, 4)
  })

  it('sun directly behind the panel (AOI > 90 degrees) contributes zero direct component', () => {
    // Panel faces south (180), sun is due north at a modest altitude —
    // physically odd but exercises the AOI clamp directly.
    const result = poaIrradiance(
      { direct: 900, diffuse: 0 },
      { altitude: 5, azimuth: 0 },
      60,
      180,
    )
    // At this geometry cos(AOI) goes negative, so only ground-reflected
    // diffuse-from-direct remains (diffuse itself is 0 here).
    const tiltRad = (60 * Math.PI) / 180
    const groundReflected = 900 * DEFAULT_ALBEDO * ((1 - Math.cos(tiltRad)) / 2)
    expect(result).toBeCloseTo(groundReflected, 4)
  })

  it('increasing tilt toward the sun increases POA up to a point, then decreases past normal incidence', () => {
    const base = { direct: 800, diffuse: 100 }
    const sun = { altitude: 40, azimuth: 180 }
    const tilts = [0, 10, 20, 30, 40, 50, 60, 70, 80, 90]
    const values = tilts.map((tilt) => poaIrradiance(base, sun, tilt, 180))
    // Optimal tilt for a sun at 40 degrees altitude, panel facing the sun's
    // azimuth exactly, is tilt = zenith = 50 degrees (normal incidence).
    const maxIndex = values.indexOf(Math.max(...values))
    expect(tilts[maxIndex]).toBe(50)
  })

  it('custom albedo changes only the ground-reflected component', () => {
    const horizontalIrradiance = { direct: 600, diffuse: 100 }
    const sun = { altitude: 45, azimuth: 180 }
    const withDefaultAlbedo = poaIrradiance(horizontalIrradiance, sun, 30, 180)
    const withZeroAlbedo = poaIrradiance(horizontalIrradiance, sun, 30, 180, 0)
    const tiltRad = (30 * Math.PI) / 180
    const expectedGroundReflected =
      (horizontalIrradiance.direct + horizontalIrradiance.diffuse) *
      DEFAULT_ALBEDO *
      ((1 - Math.cos(tiltRad)) / 2)
    expect(withDefaultAlbedo - withZeroAlbedo).toBeCloseTo(
      expectedGroundReflected,
      4,
    )
  })

  it('is a pure function: repeated calls with the same inputs return the same result', () => {
    const args: Parameters<typeof poaIrradiance> = [
      { direct: 500, diffuse: 80 },
      { altitude: 35, azimuth: 210 },
      25,
      190,
    ]
    const first = poaIrradiance(...args)
    const second = poaIrradiance(...args)
    expect(second).toBe(first)
  })

  it('result is always non-negative across a sweep of tilts, azimuths, and sun positions', () => {
    const tilts = [0, 15, 30, 45, 60, 90]
    const panelAzimuths = [90, 180, 270]
    const sunAltitudes = [-10, 0, 5, 20, 45, 90]
    const sunAzimuths = [0, 90, 180, 270]
    for (const tilt of tilts) {
      for (const panelAz of panelAzimuths) {
        for (const sunAlt of sunAltitudes) {
          for (const sunAz of sunAzimuths) {
            const result = poaIrradiance(
              { direct: 700, diffuse: 120 },
              { altitude: sunAlt, azimuth: sunAz },
              tilt,
              panelAz,
            )
            expect(result).toBeGreaterThanOrEqual(0)
          }
        }
      }
    }
  })

  it('NaN sun altitude is treated as sun-below-horizon (no direct component) rather than propagating NaN', () => {
    const result = poaIrradiance(
      { direct: 500, diffuse: 100 },
      { altitude: NaN, azimuth: 180 },
      30,
      180,
    )
    expect(Number.isNaN(result)).toBe(false)
    const tiltRad = (30 * Math.PI) / 180
    const expected =
      100 * ((1 + Math.cos(tiltRad)) / 2) +
      600 * DEFAULT_ALBEDO * ((1 - Math.cos(tiltRad)) / 2)
    expect(result).toBeCloseTo(expected, 4)
  })
})
