import { describe, expect, it } from 'vitest'
import { sunPosition } from './sunPosition'

/**
 * Reference values below were generated by an independent Python
 * transcription of NOAA's published solar position equations
 * (https://gml.noaa.gov/grad/solcalc/solareqns.PDF), written separately
 * from the TypeScript implementation under test here so the two
 * implementations don't share bugs. The formulas/coefficients were
 * additionally cross-checked term-by-term against NOAA's own solar
 * calculator source (https://gml.noaa.gov/grad/solcalc/main.js), which
 * implements the same algorithm and is what powers the public NOAA solar
 * calculator (https://gml.noaa.gov/grad/solcalc/azel.html) these values
 * are meant to match. Altitude includes NOAA's standard atmospheric
 * refraction correction, matching the calculator's displayed elevation.
 * See docs/decisions/0010-solar-position-algorithm.md for details.
 *
 * Tolerance: 0.01 degrees, per the module's target accuracy — enforced via
 * `toBeCloseTo(expected, 2)` below (max diff 0.005°). Note this tolerance
 * applies to altitude and to azimuth away from solar zenith; azimuth's
 * accuracy degrades to ~0.05-0.1 degrees near zenith because the azimuth
 * formula is inherently ill-conditioned there (see ADR 0010). None of the
 * cases below are near zenith.
 *
 * The two exactly-at/near-the-pole cases assert an exact azimuth (`toBe`,
 * not `toBeCloseTo`) because that value isn't a numerically-approximated
 * angle — it's NOAA's explicit degenerate-input guard (main.js:303-322)
 * firing and returning a fixed 180/0 based on hemisphere. See the
 * `azimuthDenom` guard in sunPosition.ts and ADR 0010's "Consequences"
 * section.
 */

describe('sunPosition', () => {
  it('equator, March equinox, mid-morning', () => {
    // lat=0, lon=0, 2024-03-20T09:00:00Z
    const result = sunPosition(0, 0, new Date('2024-03-20T09:00:00Z'))
    expect(result.altitude).toBeCloseTo(43.1851, 2)
    expect(result.azimuth).toBeCloseTo(89.8661, 2)
  })

  it('Boulder, CO (mid-latitude), summer solstice, solar noon', () => {
    // lat=40.015, lon=-105.2705, 2024-06-20T18:47:00Z (~local solar noon)
    const result = sunPosition(
      40.015,
      -105.2705,
      new Date('2024-06-20T18:47:00Z'),
    )
    expect(result.altitude).toBeCloseTo(73.0944, 2)
    expect(result.azimuth).toBeCloseTo(167.4096, 2)
  })

  it('Oslo, Norway (high latitude), winter solstice, solar noon — low sun', () => {
    // lat=59.9139, lon=10.7522, 2024-12-21T11:13:00Z (~local solar noon)
    const result = sunPosition(
      59.9139,
      10.7522,
      new Date('2024-12-21T11:13:00Z'),
    )
    expect(result.altitude).toBeCloseTo(6.7735, 2)
    expect(result.azimuth).toBeCloseTo(179.4696, 2)
  })

  it('Sydney, Australia (southern hemisphere), autumn afternoon', () => {
    // lat=-33.8688, lon=151.2093, 2024-04-15T03:30:00Z
    const result = sunPosition(
      -33.8688,
      151.2093,
      new Date('2024-04-15T03:30:00Z'),
    )
    expect(result.altitude).toBeCloseTo(40.7762, 2)
    expect(result.azimuth).toBeCloseTo(328.4701, 2)
  })

  it('Fairbanks, Alaska (near-arctic), winter, midday — very low sun', () => {
    // lat=64.8378, lon=-147.7164, 2024-12-21T21:40:00Z (~local solar noon)
    const result = sunPosition(
      64.8378,
      -147.7164,
      new Date('2024-12-21T21:40:00Z'),
    )
    expect(result.altitude).toBeCloseTo(2.0099, 2)
    expect(result.azimuth).toBeCloseTo(177.8459, 2)
  })

  it('Cape Town, South Africa (southern hemisphere), spring morning', () => {
    // lat=-33.9249, lon=18.4241, 2024-09-23T07:00:00Z
    const result = sunPosition(
      -33.9249,
      18.4241,
      new Date('2024-09-23T07:00:00Z'),
    )
    expect(result.altitude).toBeCloseTo(28.9106, 2)
    expect(result.azimuth).toBeCloseTo(68.6631, 2)
  })

  it('Berlin, Germany, mid-afternoon (post-solar-noon, hourAngle > 0)', () => {
    // lat=52.52, lon=13.405, 2024-06-20T15:00:00Z (Berlin, mid-afternoon)
    const result = sunPosition(52.52, 13.405, new Date('2024-06-20T15:00:00Z'))
    expect(result.altitude).toBeCloseTo(37.7355, 2)
    expect(result.azimuth).toBeCloseTo(259.5042, 2)
  })

  it('Denver, CO, afternoon — additional azimuth spread (west-southwest)', () => {
    // lat=39.7392, lon=-104.9903, 2024-09-23T22:00:00Z
    const result = sunPosition(
      39.7392,
      -104.9903,
      new Date('2024-09-23T22:00:00Z'),
    )
    expect(result.altitude).toBeCloseTo(31.2544, 2)
    expect(result.azimuth).toBeCloseTo(238.7735, 2)
  })

  it('Nairobi, Kenya — additional azimuth spread (near north)', () => {
    // lat=-1.2833, lon=36.8167, 2024-06-20T09:00:00Z
    const result = sunPosition(
      -1.2833,
      36.8167,
      new Date('2024-06-20T09:00:00Z'),
    )
    expect(result.altitude).toBeCloseTo(63.9086, 2)
    expect(result.azimuth).toBeCloseTo(18.1789, 2)
  })

  it('Boulder, CO, below the horizon at night — exercises the atmospheric refraction branch for elevation <= -0.575deg', () => {
    // lat=40.015, lon=-105.2705, 2024-06-21T05:00:00Z (deep night)
    const result = sunPosition(
      40.015,
      -105.2705,
      new Date('2024-06-21T05:00:00Z'),
    )
    expect(result.altitude).toBeCloseTo(-20.3632, 2)
    expect(result.azimuth).toBeCloseTo(329.9855, 2)
  })

  it('exactly at the north pole — degenerate azimuth denominator, matches NOAA guard (fixed 180deg, not a plausible-looking interpolated value)', () => {
    // lat=90, lon=0, 2024-06-20T12:00:00Z
    const result = sunPosition(90, 0, new Date('2024-06-20T12:00:00Z'))
    expect(result.altitude).toBeCloseTo(23.4751, 2)
    expect(result.azimuth).toBe(180)
  })

  it('0.0001deg from the north pole — same degenerate-azimuth guard applies, no 180deg discontinuity vs. lat=90', () => {
    // lat=89.9999, lon=0, 2024-06-20T12:00:00Z
    const result = sunPosition(89.9999, 0, new Date('2024-06-20T12:00:00Z'))
    expect(result.altitude).toBeCloseTo(23.4752, 2)
    expect(result.azimuth).toBe(180)
  })

  it('0.0001deg from the south pole — degenerate-azimuth guard, southern-hemisphere fixed value', () => {
    // lat=-89.9999, lon=0, 2024-06-20T12:00:00Z
    const result = sunPosition(-89.9999, 0, new Date('2024-06-20T12:00:00Z'))
    expect(result.altitude).toBeCloseTo(-23.4247, 2)
    expect(result.azimuth).toBe(0)
  })

  it('is a pure function: repeated calls with the same inputs return the same result', () => {
    const date = new Date('2024-06-20T18:47:00Z')
    const first = sunPosition(40.015, -105.2705, date)
    const second = sunPosition(40.015, -105.2705, date)
    expect(second).toEqual(first)
  })
})
