import { describe, expect, it } from 'vitest'
import { sunPosition } from './sunPosition'

/**
 * Reference values below were generated by an independent Python
 * transcription of NOAA's published solar position equations
 * (https://gml.noaa.gov/grad/solcalc/solareqns.PDF), written separately
 * from the TypeScript implementation under test here so the two
 * implementations don't share bugs. The formulas/coefficients were
 * additionally cross-checked term-by-term against NOAA's own solar
 * calculator source (https://gml.noaa.gov/grad/solcalc/main.js), which
 * implements the same algorithm and is what powers the public NOAA solar
 * calculator (https://gml.noaa.gov/grad/solcalc/azel.html) these values
 * are meant to match. Altitude includes NOAA's standard atmospheric
 * refraction correction, matching the calculator's displayed elevation.
 * See docs/decisions/0010-solar-position-algorithm.md for details.
 *
 * Tolerance: 0.01 degrees, per the module's target accuracy — enforced via
 * `toBeCloseTo(expected, 2)` below (max diff 0.005°).
 */

describe('sunPosition', () => {
  it('equator, March equinox, mid-morning', () => {
    // lat=0, lon=0, 2024-03-20T09:00:00Z
    const result = sunPosition(0, 0, new Date('2024-03-20T09:00:00Z'))
    expect(result.altitude).toBeCloseTo(43.1851, 2)
    expect(result.azimuth).toBeCloseTo(89.8661, 2)
  })

  it('Boulder, CO (mid-latitude), summer solstice, solar noon', () => {
    // lat=40.015, lon=-105.2705, 2024-06-20T18:47:00Z (~local solar noon)
    const result = sunPosition(
      40.015,
      -105.2705,
      new Date('2024-06-20T18:47:00Z'),
    )
    expect(result.altitude).toBeCloseTo(73.0944, 2)
    expect(result.azimuth).toBeCloseTo(167.4096, 2)
  })

  it('Oslo, Norway (high latitude), winter solstice, solar noon — low sun', () => {
    // lat=59.9139, lon=10.7522, 2024-12-21T11:13:00Z (~local solar noon)
    const result = sunPosition(
      59.9139,
      10.7522,
      new Date('2024-12-21T11:13:00Z'),
    )
    expect(result.altitude).toBeCloseTo(6.7735, 2)
    expect(result.azimuth).toBeCloseTo(179.4696, 2)
  })

  it('Sydney, Australia (southern hemisphere), autumn afternoon', () => {
    // lat=-33.8688, lon=151.2093, 2024-04-15T03:30:00Z
    const result = sunPosition(
      -33.8688,
      151.2093,
      new Date('2024-04-15T03:30:00Z'),
    )
    expect(result.altitude).toBeCloseTo(40.7762, 2)
    expect(result.azimuth).toBeCloseTo(328.4701, 2)
  })

  it('Fairbanks, Alaska (near-arctic), winter, midday — very low sun', () => {
    // lat=64.8378, lon=-147.7164, 2024-12-21T21:40:00Z (~local solar noon)
    const result = sunPosition(
      64.8378,
      -147.7164,
      new Date('2024-12-21T21:40:00Z'),
    )
    expect(result.altitude).toBeCloseTo(2.0099, 2)
    expect(result.azimuth).toBeCloseTo(177.8459, 2)
  })

  it('Cape Town, South Africa (southern hemisphere), spring morning', () => {
    // lat=-33.9249, lon=18.4241, 2024-09-23T07:00:00Z
    const result = sunPosition(
      -33.9249,
      18.4241,
      new Date('2024-09-23T07:00:00Z'),
    )
    expect(result.altitude).toBeCloseTo(28.9106, 2)
    expect(result.azimuth).toBeCloseTo(68.6631, 2)
  })

  it('is a pure function: repeated calls with the same inputs return the same result', () => {
    const date = new Date('2024-06-20T18:47:00Z')
    const first = sunPosition(40.015, -105.2705, date)
    const second = sunPosition(40.015, -105.2705, date)
    expect(second).toEqual(first)
  })
})
