/**
 * Public types for the `simulation` module. See `runTmySimulation.ts` for
 * the orchestration logic that produces {@link SimulationResult}, and
 * `docs/decisions/0040-tmy-disaggregation-approach.md` for the modeling
 * choices behind this shape.
 */

/** A geographic location, in decimal degrees. */
export interface Location {
  /** Latitude, positive north (-90 to 90). */
  lat: number
  /** Longitude, positive east (-180 to 180). */
  lon: number
}

/**
 * PV system configuration. Field names/shape are kept consistent with
 * `src/ui/SystemConfigForm`'s `SystemConfig` type (issue #13 / PR #28),
 * with `panelCount` + `wattsPerPanel` replacing that type's single-preset
 * framing so this module doesn't need to depend on `panel-presets/` or
 * `ui/` — per the settled project-owner decision (see issue #9), the
 * simulation's rated system capacity is `panelCount * wattsPerPanel`.
 */
export interface SystemConfig {
  /** Panel tilt from horizontal, in degrees (0 = flat, 90 = vertical). */
  tiltDeg: number
  /** Panel azimuth, in degrees clockwise from true north (180 = due south). */
  azimuthDeg: number
  /** Number of panels in the array. */
  panelCount: number
  /** Rated power per panel at STC, in watts-peak. */
  wattsPerPanel: number
  /** Module efficiency at STC, as a percentage. Not used in the power
   * calculation (see `solar-physics/panelPowerOutput`'s `PanelSpec` doc) —
   * kept here for shape-compatibility with the UI's config type and for
   * display purposes. */
  efficiencyPercent: number
  /** Temperature coefficient of power (Pmax), in %/°C. Negative for real panels. */
  tempCoefficientPercentPerC: number
  /** Aggregate system losses (wiring, inverter, soiling, mismatch, etc.), as a percentage. */
  systemLossesPercent: number
  /**
   * Manual shading derate, as a percentage — a user-estimated stand-in for
   * real geometric shadow-casting (deferred to M3, see the M1 design spec's
   * roadmap section). Stacked multiplicatively with `systemLossesPercent`,
   * as a second independent derate factor rather than summed with it — see
   * `docs/decisions/0040-tmy-disaggregation-approach.md`.
   */
  manualShadingPercent: number
}

/** One hour of a representative day's simulated output. */
export interface HourlyPoint {
  /** Hour of day, 0-23 (UTC — see the ADR's note on the representative-day convention). */
  hour: number
  /** Plane-of-array irradiance for this hour, in W/m². */
  poaIrradianceWm2: number
  /** Panel array power output for this hour, in watts. */
  powerW: number
}

/** Simulated results for one calendar month's representative day. */
export interface MonthlySimulation {
  /** Calendar month, 1 (January) through 12 (December). */
  month: number
  /** Day-of-year (1-366) of this month's representative day in the fixed reference year — see `REFERENCE_YEAR`. Intended as the heatmap's sparse day-of-year axis value for this month. */
  dayOfYear: number
  /** Flat ambient temperature used for every hour of the representative day, taken directly from the month's climate normal. */
  ambientTemperatureC: number
  /** Clearness scale factor applied to clear-sky irradiance to approximate this month's real-world average conditions, clamped to `[0, 1.2]` — see the ADR. */
  clearnessFactor: number
  /** Hourly curve for the representative day, 24 entries (hour 0-23). */
  representativeDayHourly: HourlyPoint[]
  /** Total energy generated by the representative day, in kWh. */
  representativeDayTotalKWh: number
  /** Number of calendar days in this month, in the fixed reference year. */
  daysInMonth: number
  /** Estimated monthly total energy: `representativeDayTotalKWh * daysInMonth`, in kWh. */
  monthlyTotalKWh: number
}

/**
 * Full TMY (long-term climate-normal) simulation result: a representative
 * day per available calendar month, plus monthly and annual aggregates.
 * Designed to be consumed directly by the Daily (#14), Monthly (#15), and
 * Heatmap (#16) chart tabs.
 */
export interface SimulationResult {
  location: Location
  systemConfig: SystemConfig
  /**
   * Fixed calendar year used to derive each representative day's date and
   * days-in-month — see `REFERENCE_YEAR`. Not a forecast year; TMY data has
   * no real year attached, this just anchors calendar arithmetic.
   */
  referenceYear: number
  /**
   * Per-month simulation results, one entry per month NASA POWER had
   * usable data for (1-12 entries, ascending by `month` — see
   * `MonthlyClimateNormal`'s "months may be dropped" note). Index by the
   * `month` field, not array position.
   */
  months: MonthlySimulation[]
  /** Estimated total annual energy generation, summed across `months`, in kWh. */
  annualTotalKWh: number
}
